BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyACM0
USER_LIB_PATH := $(realpath /home/michal/Projects/Arduino/libraries)
ARDUINO_LIBS = Time Menu Wire DS1307RTC LiquidCrystal Button

include $(ARDMK_DIR)/Arduino.mk
