BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyACM0
USER_LIB_PATH := $(realpath /home/michal/Working/libraries)
ARDUINO_LIBS = EEPROM Time Menu Events Wire DS1307RTC LiquidCrystal NESpad Button SD MemoryFree ctime

include $(ARDMK_DIR)/Arduino.mk
